version: '3.8'

services:
    backend:
        build: .
        env_file: .env
        ports:
            - 8080:8080
            - 9229:9229 # debugger port
        volumes:
            - .:/usr/src/app
            - /usr/src/app/.pnpm-store
            - /usr/src/app/node_modules
        command: pnpm start:docker
